# Fish shell completions for ledger
#
# To install for current user:
#   cp ledger.fish ~/.config/fish/completions/ledger.fish

# Disable file completion by default
complete -c ledger -f

# All subcommands, for use in conditions
set -l subcmds accounts balance budget cleared commodities convert csv draft echo emacs entry equity lisp org payees pricemap prices pricesdb print register reload select source stats tags xact xml

# Commands - only shown before a subcommand has been given
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a accounts -d 'List all accounts'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a balance -d 'Show account balances'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a budget -d 'Show budget report'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a cleared -d 'Show cleared transactions'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a commodities -d 'List all commodities'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a convert -d 'Convert data to ledger format'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a csv -d 'Output in CSV format'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a draft -d 'Generate a new transaction draft'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a echo -d 'Echo arguments'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a emacs -d 'Output in Emacs lisp format'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a entry -d 'Generate a new transaction entry'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a equity -d 'Output equity transactions'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a lisp -d 'Output in lisp format'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a org -d 'Output in Org mode format'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a payees -d 'List all payees'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a pricemap -d 'Output price map'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a prices -d 'Show price history'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a pricesdb -d 'Show prices in pricesdb format'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a print -d 'Print transactions'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a register -d 'Show account register'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a reload -d 'Reload the journal'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a select -d 'Select transactions using SQL-like syntax'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a source -d 'Show source transactions'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a stats -d 'Show journal statistics'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a tags -d 'List all tags'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a xact -d 'Generate a new transaction'
complete -c ledger -n "not __fish_seen_subcommand_from $subcmds" -a xml -d 'Output in XML format'

# Account names after commands that filter by account
complete -c ledger -n "__fish_seen_subcommand_from balance equity print register" -a 'Assets Liabilities Equity Revenue Expenses' -d Account

# Options (no argument)
complete -c ledger -l actual -d 'Consider only actual transactions'
complete -c ledger -l actual-dates -d 'Use actual dates'
complete -c ledger -l add-budget -d 'Add unbudgeted accounts to budget report'
complete -c ledger -l amount-data -d 'Show only amount data'
complete -c ledger -l anon -d 'Anonymize journal'
complete -c ledger -l ansi -d 'Use ANSI escape codes'
complete -c ledger -l args-only -d 'Use only command-line arguments'
complete -c ledger -l auto-match -d 'Automatically match transactions'
complete -c ledger -l aux-date -d 'Use auxiliary dates'
complete -c ledger -l average -d 'Show average values'
complete -c ledger -l base -d 'Report in base commodity'
complete -c ledger -l basis -d 'Report basis values'
complete -c ledger -l budget -d 'Show budget report'
complete -c ledger -l by-payee -d 'Group results by payee'
complete -c ledger -l change -d 'Show balance changes'
complete -c ledger -l check-payees -d 'Check payee names'
complete -c ledger -l cleared -d 'Consider only cleared transactions'
complete -c ledger -l collapse -d 'Collapse entries with multiple transactions'
complete -c ledger -l collapse-if-zero -d 'Collapse entry if net is zero'
complete -c ledger -l color -d 'Use color in output'
complete -c ledger -l cost -d 'Show cost basis'
complete -c ledger -l count -d 'Show count of entries'
complete -c ledger -l current -d 'Show only current transactions'
complete -c ledger -l daily -d 'Report by day'
complete -c ledger -l day-break -d 'Break entries at day boundaries'
complete -c ledger -l days-of-week -d 'Show days of week'
complete -c ledger -l dc -d 'Separate debits and credits'
complete -c ledger -l decimal-comma -d 'Use comma as decimal separator'
complete -c ledger -l detail -d 'Show detailed report'
complete -c ledger -l deviation -d 'Show deviations'
complete -c ledger -l dow -d 'Show day of week'
complete -c ledger -l download -d 'Download prices'
complete -c ledger -l effective -d 'Use effective dates'
complete -c ledger -l empty -d 'Include empty accounts'
complete -c ledger -l equity -d 'Show equity'
complete -c ledger -l exact -d 'Compute exact values'
complete -c ledger -l explicit -d 'Be explicit about what is calculated'
complete -c ledger -l flat -d 'Do not flatten hierarchical account names'
complete -c ledger -l force-color -d 'Force color output'
complete -c ledger -l force-pager -d 'Force use of pager'
complete -c ledger -l full-help -d 'Show full help'
complete -c ledger -l gain -d 'Show unrealized gains'
complete -c ledger -l generated -d 'Include generated transactions'
complete -c ledger -l help -d 'Show help'
complete -c ledger -l help-calc -d 'Show calculation help'
complete -c ledger -l help-comm -d 'Show commodity help'
complete -c ledger -l help-disp -d 'Show display help'
complete -c ledger -l historical -d 'Value commodities historically'
complete -c ledger -l immediate -d 'Evaluate calculations immediately'
complete -c ledger -l invert -d 'Invert sign of amounts'
complete -c ledger -l lot-dates -d 'Show lot dates'
complete -c ledger -l lot-notes -d 'Show lot notes'
complete -c ledger -l lot-prices -d 'Show lot prices'
complete -c ledger -l lot-tags -d 'Show lot tags'
complete -c ledger -l lots -d 'Report lot information'
complete -c ledger -l lots-actual -d 'Report actual lot information'
complete -c ledger -l market -d 'Show market value'
complete -c ledger -l monthly -d 'Report by month'
complete -c ledger -l no-aliases -d 'Disable account aliases'
complete -c ledger -l no-color -d 'Disable color output'
complete -c ledger -l no-pager -d 'Disable pager'
complete -c ledger -l no-rounding -d 'Disable rounding'
complete -c ledger -l no-titles -d 'Disable titles'
complete -c ledger -l no-total -d 'Disable total line'
complete -c ledger -l options -d 'Show options'
complete -c ledger -l pedantic -d 'Be pedantic about format'
complete -c ledger -l pending -d 'Consider only pending transactions'
complete -c ledger -l percent -d 'Show percentages'
complete -c ledger -l permissive -d 'Be permissive about format'
complete -c ledger -l price -d 'Show price'
complete -c ledger -l primary-date -d 'Use primary dates'
complete -c ledger -l quantity -d 'Report commodities as quantities'
complete -c ledger -l quarterly -d 'Report by quarter'
complete -c ledger -l raw -d 'Output raw data'
complete -c ledger -l real -d 'Consider only real transactions'
complete -c ledger -l recursive-aliases -d 'Expand aliases recursively'
complete -c ledger -l related -d 'Show related transactions'
complete -c ledger -l related-all -d 'Show all related transactions'
complete -c ledger -l revalued -d 'Show revalued transactions'
complete -c ledger -l revalued-only -d 'Show only revalued transactions'
complete -c ledger -l rich-data -d 'Include rich metadata in output'
complete -c ledger -l strict -d 'Be strict about account names'
complete -c ledger -l subtotal -d 'Collapse entries into subtotals'
complete -c ledger -l time-colon -d 'Use colon notation for time'
complete -c ledger -l time-report -d 'Show time report'
complete -c ledger -l total-data -d 'Show only total data'
complete -c ledger -l unbudgeted -d 'Show unbudgeted transactions'
complete -c ledger -l uncleared -d 'Consider only uncleared transactions'
complete -c ledger -l unrealized -d 'Show unrealized gains and losses'
complete -c ledger -l unround -d 'Disable rounding'
complete -c ledger -l value -d 'Show market value'
complete -c ledger -l values -d 'Show values'
complete -c ledger -l verbose -d 'Verbose output'
complete -c ledger -l verify -d 'Verify calculations'
complete -c ledger -l verify-memory -d 'Verify memory usage'
complete -c ledger -l version -d 'Show version'
complete -c ledger -l weekly -d 'Report by week'
complete -c ledger -l wide -d 'Wide output format'
complete -c ledger -l yearly -d 'Report by year'

# Options that require an argument
complete -c ledger -l abbrev-len -r -d 'Abbreviate account names to this length'
complete -c ledger -l account -r -d 'Specify account'
complete -c ledger -l account-width -r -d 'Account column width'
complete -c ledger -l amount -r -d 'Value expression for amounts'
complete -c ledger -l amount-width -r -d 'Amount column width'
complete -c ledger -l balance-format -r -d 'Format for balance reports'
complete -c ledger -l begin -r -d 'Start date'
complete -c ledger -l bold-if -r -d 'Make output bold if expression is true'
complete -c ledger -l budget-format -r -d 'Format for budget reports'
complete -c ledger -l cleared-format -r -d 'Format for cleared reports'
complete -c ledger -l columns -r -d 'Number of columns'
complete -c ledger -l csv-format -r -d 'Format for CSV output'
complete -c ledger -l date -r -d 'Specify date'
complete -c ledger -l date-format -r -d 'Date output format'
complete -c ledger -l date-width -r -d 'Date column width'
complete -c ledger -l datetime-format -r -d 'Datetime output format'
complete -c ledger -l debug -r -d 'Enable debug output'
complete -c ledger -l depth -r -d 'Limit report depth'
complete -c ledger -l display -r -d 'Filter expression for display'
complete -c ledger -l display-amount -r -d 'Value expression for displayed amounts'
complete -c ledger -l display-total -r -d 'Value expression for displayed totals'
complete -c ledger -l end -r -d 'End date'
complete -c ledger -l exchange -r -d 'Exchange commodity'
complete -c ledger -l first -r -d 'Show only first N entries'
complete -c ledger -l forecast -r -d 'Forecast expression'
complete -c ledger -l forecast-while -r -d 'Forecast while expression is true'
complete -c ledger -l forecast-years -r -d 'Number of years to forecast'
complete -c ledger -l format -r -d 'Output format'
complete -c ledger -l group-by -r -d 'Group results by expression'
complete -c ledger -l group-title-format -r -d 'Format for group titles'
complete -c ledger -l head -r -d 'Show first N transactions'
complete -c ledger -l inject -r -d 'Inject data'
complete -c ledger -l input-date-format -r -d 'Input date format'
complete -c ledger -l last -r -d 'Show only last N entries'
complete -c ledger -l leeway -r -d 'Leeway for date matching'
complete -c ledger -l limit -r -d 'Limit transactions with expression'
complete -c ledger -l master-account -r -d 'Name of the master account'
complete -c ledger -l meta -r -d 'Show metadata'
complete -c ledger -l meta-width -r -d 'Metadata column width'
complete -c ledger -l now -r -d 'Use this date as now'
complete -c ledger -l only -r -d 'Filter transactions with expression'
complete -c ledger -l payee -r -d 'Filter by payee'
complete -c ledger -l payee-width -r -d 'Payee column width'
complete -c ledger -l period -r -d 'Reporting period'
complete -c ledger -l period-sort -r -d 'Sort within periods'
complete -c ledger -l pivot -r -d 'Pivot report by tag'
complete -c ledger -l plot-amount-format -r -d 'Format for plot amount output'
complete -c ledger -l plot-total-format -r -d 'Format for plot total output'
complete -c ledger -l prepend-format -r -d 'Format to prepend to output'
complete -c ledger -l prepend-width -r -d 'Width of prepended columns'
complete -c ledger -l price-exp -r -d 'Price expression'
complete -c ledger -l pricedb-format -r -d 'Format for pricesdb output'
complete -c ledger -l prices-format -r -d 'Format for prices output'
complete -c ledger -l register-format -r -d 'Format for register reports'
complete -c ledger -l revalued-total -r -d 'Revalued total expression'
complete -c ledger -l seed -r -d 'Random seed'
complete -c ledger -l sort -r -d 'Sort expression'
complete -c ledger -l sort-all -r -d 'Sort all transactions'
complete -c ledger -l sort-xacts -r -d 'Sort transactions within entries'
complete -c ledger -l start-of-week -r -d 'First day of week'
complete -c ledger -l tail -r -d 'Show last N transactions'
complete -c ledger -l total -r -d 'Value expression for totals'
complete -c ledger -l total-width -r -d 'Total column width'
complete -c ledger -l trace -r -d 'Enable trace output'
complete -c ledger -l truncate -r -d 'Truncation style'
complete -c ledger -l unrealized-gains -r -d 'Account for unrealized gains'
complete -c ledger -l unrealized-losses -r -d 'Account for unrealized losses'
complete -c ledger -l value-expr -r -d 'Value expression'

# Options that take file arguments (re-enable file completion with -F)
complete -c ledger -l cache -r -F -d 'Use cache file'
complete -c ledger -l file -s f -r -F -d 'Journal file to read'
complete -c ledger -l init-file -s i -r -F -d 'Initialization file'
complete -c ledger -l output -s o -r -F -d 'Output to file'
complete -c ledger -l pager -r -F -d 'Pager program'
complete -c ledger -l price-db -r -F -d 'Price database file'
complete -c ledger -l script -r -F -d 'Script file to execute'
